### ISSUE TITLE
renaming a running file causes down to fail

### ISSUE THREAD

**Issue by dsm1212** [OpenMediaVault-Plugin-Developers/openmediavault-compose#2]
Take these as enhancements although the first one is arguably a bug:

1. While setting things up I decided to rename a file. Later I hit down on that file and it couldn't find anything. Fortunately I remembered the previous name so I named it back hit down and things stopped. If you can't track the name change probably it should be disallowed when running. 
2. Portainer indicates which stacks are running with an orange Inactive label next to the stacks not in use. That is quite handy when you have a numbe of stacks and some that you don't keep running all the time. A colored label on the state column of the container list would be nice too. I see healthy i the status column next to uptime. Is that where unhealthy will show too? Portainer consolidates healthy/unhealthy/running and that was a minor convenience to look at one thing.
3. I notice I can type the name of a stack in the container list to see it's containers. A pick list for that would be better. Otherwise I have to remember the names exactly and type them a ton of times.
4. small thing but I can't get all 31 containers on the container list like I could with portainer. Its a bit of a nuisance to paginate. Could you allow more rows and maybe remove a little whitespace? It looks like I could get 3-4 rows for each one displayed. The column widths are all equal and the image column frequently spans two rows even though there is a ton of space around service and state.
5. The Project column on the containers window is the compose file name. Why Project?
6. The 3 memory and IO columns on the stats page sort alphabetically and this is pretty useless. 

Seems good so far. Thanks

**Comment by ryecoaaron** [comment]
1.  I will have to disallow altogether since the name change doesn't take effect until you apply.
2. Does the Containers tab not have all of this?  I know it doesn't do coloring but that isn't really an option in OMV.  I think a single status for a compose/stack doesn't make sense since each container should have a status
3. That isn't an option in the framework.  You only have to type a portion of the name and you can sort containers by name making it just as easy to find as a dropdown would be.  Really long dropdowns are not efficient either.
4. While I can change add more rows, it wouldn't be adjustable to user taste.  I prefer 25 rows since everything else in omv is set to that.  I can try to optimize the column width a bit more but each row will often be multiple rows since the ports will always be separated by linefeeds.
5. On your compose/stacks it might be but not mine.  If yours are all duplicates, you can hide the column.
6. I just added the sort feature to all of the columns.  The I/O columns will have to be separated to be sorted but even then they are not returned as numbers making it harder to sort correctly.  So, i will likely just remove the sort feature but I really don't think it hurts anything to be on there.

**Comment by ryecoaaron** [comment]
All of these that can be fixed have been fixed in 6.7.7 in the repo now.

**Comment by dsm1212** [comment]
Thanks!
