### ISSUE TITLE
CHANGE_TO_COMPOSE_NAME does not always trigger replacement

### ISSUE THREAD

**Issue by DjoeC** [OpenMediaVault-Plugin-Developers/openmediavault-compose#43]
The meta-variable CHANGE_TO_COMPOSE_NAME which was introduced in compose version 7.1.3 does not always get replaced with the name of the compose file.  Reason unknown, it seems inconsistent behaviour.

yml file attached.  Composefile name = Image name = Dockerfile name, image is based on Python 3.13 image.  A 2nd compose file had similar problems but they resolved after a server restart which currently does not resolve the issue.  Problem started/was noticed for the first time about 1-2 weeks ago.

[domodedup.yml.txt](https://github.com/user-attachments/files/18260813/domodedup.yml.txt)

**Comment by ryecoaaron** [comment]
I actually wanted to get rid of CHANGE_TO_COMPOSE_NAME since CHANGE_TO_COMPOSE_DATA_PATH was supposed to replace it.  I didn't see a good use case for the former and almost no one was using it.

The issue you are seeing is caused by the fast write introduced [here](https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-compose/commit/65a5acdc028ce4111ecb5b4b0ddbe3237dda6dde) because it does not support the CHANGE_TO_COMPOSE_NAME (only the saltstack still supports it).

While I understand what you are doing, I'm not sure why?  Since a compose file is only used for one file in the plugin, basically having a template doesn't really help.  I understand that it makes one or more of your compose files the same but plugging in the name instead of the replace string seems like the same amount of effort.

**Comment by ryecoaaron** [comment]
Ok, it was an easy change to add the replace to the fast change code.  I will leave support.
https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-compose/commit/e724e77b9a965b83af36441fd9444b994fc3911b

this will go out in the next version.

**Comment by DjoeC** [comment]
> I actually wanted to get rid of CHANGE_TO_COMPOSE_NAME since CHANGE_TO_COMPOSE_DATA_PATH was supposed to replace it. I didn't see a good use case for the former and almost no one was using it.
> 
> The issue you are seeing is caused by the fast write introduced [here](https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-compose/commit/65a5acdc028ce4111ecb5b4b0ddbe3237dda6dde) because it does not support the CHANGE_TO_COMPOSE_NAME (only the saltstack still supports it).
> 
> While I understand what you are doing, I'm not sure why? Since a compose file is only used for one file in the plugin, basically having a template doesn't really help. I understand that it makes one or more of your compose files the same but plugging in the name instead of the replace string seems like the same amount of effort.

I'm glad you didn't get rid of it.  All my containers are based on this variable.  We've had the discussion about usability in the OMV forum right before CHANGE_TO_COMPOSE_NAME got introduced: https://forum.openmediavault.org/index.php?thread/52062-environment-variables-for-compose-settings-shared-folders-and-file-name

Thanks for fixing this!
